// Русские языковые переменные
// Localized Авторские права (C) 2006 - 2009 Joom.Ru - Русский Дом Joomla! Все права защищены.
// Локализатор: (c) Oleg M. (joomru@gmail.com)
// Последнее изменение 08.07.2009

tinyMCE.addI18n('ru.advanced',{
style_select:"- Стили -",
font_size:"- Размер шрифта -",
fontdefault:"- Тип шрифта -",
block:"- Формат -",
paragraph:"Абзац",
div:"Div",
address:"Адрес",
pre:"Форматированный",
h1:"Заголовок 1",
h2:"Заголовок 2",
h3:"Заголовок 3",
h4:"Заголовок 4",
h5:"Заголовок 5",
h6:"Заголовок 6",
blockquote:"Цитата",
code:"Код",
samp:"Пример кода",
dt:"Термин ",
dd:"Определение термина",
bold_desc:"Полужирный (Ctrl+B)",
italic_desc:"Курсив (Ctrl+I)",
underline_desc:"Подчеркнутый (Ctrl+U)",
striketrough_desc:"Перечеркнутый",
justifyleft_desc:"Выровнять по левому краю",
justifycenter_desc:"Выровнять по центру",
justifyright_desc:"Выровнять по правому краю",
justifyfull_desc:"Выровнять по ширине",
bullist_desc:"Маркированный список",
numlist_desc:"Нумерованный список",
outdent_desc:"Уменьшить отступ",
indent_desc:"Увеличить отступ",
undo_desc:"Отменить (Ctrl+Z)",
redo_desc:"Повторить (Ctrl+Y)",
link_desc:"Вставить/изменить ссылку",
unlink_desc:"Удалить ссылку",
image_desc:"Вставить/изменить изображение",
cleanup_desc:"Вычистить грязный код",
code_desc:"Изменить исходный код HTML",
sub_desc:"Нижний индекс",
sup_desc:"Верхний индекс",
hr_desc:"Вставить горизонтальный разделитель",
removeformat_desc:"Удалить форматирование",
custom1_desc:"Ваше описание",
forecolor_desc:"Выберите цвет текста",
backcolor_desc:"Выберите цвет фона",
charmap_desc:"Вставить символ",
visualaid_desc:"Включить/Выключить вспомогательные невидимые элементы",
anchor_desc:"Вставить/изменить якорь",
cut_desc:"Вырезать",
copy_desc:"Копировать",
paste_desc:"Вставить",
image_props_desc:"Свойства изображения",
newdocument_desc:"Новый документ",
help_desc:"Помощь",
blockquote_desc:"Цитата",
clipboard_msg:"Копирование, вырезание и вставка не доступны в браузерах Mozilla и Firefox.\r\nХотите больше узнать об этой проблеме?",
path:"Путь",
newdocument:"Вы действительно хотите очистить все содержимое?",
toolbar_focus:"Переместить фокус на панель инструментов - Alt+Q, Переместить фокус в редактор - Alt-Z, Переместить фокус на элемент пути - Alt-X",
more_colors:"Другие цвета"
});