// Русские языковые переменные
// Localized Авторские права (C) 2006 - 2009 Joom.Ru - Русский Дом Joomla! Все права защищены.
// Локализатор: (c) Oleg M. (joomru@gmail.com)
// Последнее изменение 08.07.2009

tinyMCE.addI18n('ru.advanced_dlg',{
about_title:"О TinyMCE",
about_general:"О программе",
about_help:"Помощь",
about_license:"Лицензия",
about_plugins:"Плагины",
about_plugin:"Плагин",
about_author:"Автор",
about_version:"Версия",
about_loaded:"Загруженные плагины",
anchor_title:"Вставить/изменить якорь",
anchor_name:"Название якоря",
code_title:"Редактор HTML-кода",
code_wordwrap:"Перенос по словам",
colorpicker_title:"Выберите цвет",
colorpicker_picker_tab:"Выбор",
colorpicker_picker_title:"Выбор цвета",
colorpicker_palette_tab:"Палитра",
colorpicker_palette_title:"Палитра цветов",
colorpicker_named_tab:"Именованные",
colorpicker_named_title:"Именованные цвета",
colorpicker_color:"Цвет:",
colorpicker_name:"Название:",
charmap_title:"Выберите символ",
image_title:"Вставить/изменить изображение",
image_src:"URL изображения",
image_alt:"Описание изображения",
image_list:"Список изображений",
image_border:"Граница",
image_dimensions:"Размеры",
image_vspace:"Отступ по вертикали",
image_hspace:"Отступ по горизонтали",
image_align:"Выравнивание",
image_align_baseline:"Базовая линия",
image_align_top:"Вверху",
image_align_middle:"Посередине",
image_align_bottom:"Внизу",
image_align_texttop:"По верхнему краю текста",
image_align_textbottom:"По нижнему краю текста",
image_align_left:"Слева",
image_align_right:"Справа",
link_title:"Вставить/изменить ссылку",
link_url:"URL ссылки",
link_target:"Цель",
link_target_same:"Открыть ссылку в этом окне",
link_target_blank:"Открыть ссылку в новом окне",
link_titlefield:"Заголовок",
link_is_email:"Введенный URL содержит адрес email. Добавить к нему префикс mailto: ?",
link_is_external:"Введенный URL содержит внешнюю ссылку. Добавить к ней необходимый префикс http:// ?",
link_list:"Список ссылок"
});