// Русские языковые переменные
// Localized Авторские права (C) 2006 - 2009 Joom.Ru - Русский Дом Joomla! Все права защищены.
// Локализатор: (c) Oleg M. (joomru@gmail.com)
// Последнее изменение 08.07.2009

tinyMCE.addI18n('ru.advlink_dlg',{
title:"Вставить/изменить ссылку",
url:"URL ссылки",
target:"Цель",
titlefield:"Заголовок",
is_email:"Введенный URL содержит адрес email. Добавить к нему префикс mailto: ?",
is_external:"Введенный URL содержит внешнюю ссылку. Добавить к ней необходимый префикс http:// ?",
list:"Список ссылок",
general_tab:"Основные",
popup_tab:"Всплывающие окна",
events_tab:"События",
advanced_tab:"Дополнительные",
general_props:"Основные настройки",
popup_props:"Свойства всплывающего окна",
event_props:"События",
advanced_props:"Дополнительные настройки",
popup_opts:"Параметры",
anchor_names:"Якоря",
target_same:"Открывать в этом окне / фрейме",
target_parent:"Открывать в родительском окне / фрейме",
target_top:"Открывать в верхнем фрейме (заменять все фреймы)",
target_blank:"Открывать в новом окне",
popup:"Всплывающее окно Javascript",
popup_url:"URL всплывающего окна",
popup_name:"Название окна",
popup_return:"Вставить 'return false'",
popup_scrollbars:"Показать полосы прокрутки",
popup_statusbar:"Показать статусную строку",
popup_toolbar:"Показать панели инструментов",
popup_menubar:"Показать панель меню",
popup_location:"Показать строку адреса",
popup_resizable:"Изменяющийся размер окна",
popup_dependent:"Зависимость (только Mozilla/Firefox)",
popup_size:"Размер",
popup_position:"Расположение (X/Y)",
id:"Id",
style:"Стиль",
classes:"Классы",
target_name:"Название цели",
langdir:"Направление текста",
target_langcode:"Язык цели",
langcode:"Код языка",
encoding:"Кодировка символов цели",
mime:"MIME-тип цели",
rel:"Связь страницы с целью",
rev:"Связь цели со страницей",
tabindex:"Индекс таблицы",
accesskey:"Быстрая клавиша",
ltr:"Слева направо",
rtl:"Справа налево",
link_list:"Список ссылок"
});