// Русские языковые переменные
// Localized Авторские права (C) 2006 - 2009 Joom.Ru - Русский Дом Joomla! Все права защищены.
// Локализатор: (c) Oleg M. (joomru@gmail.com)
// Последнее изменение 16.07.2009

tinyMCE.addI18n('ru.fullpage_dlg',{
title:"Свойства документа",
meta_tab:"Основные",
appearance_tab:"Внешний вид",
advanced_tab:"Дополнительные",
meta_props:"Мета-данные",
langprops:"Язык и кодировка",
meta_title:"Заголовок",
meta_keywords:"Ключевые слова",
meta_description:"Описание",
meta_robots:"Robots",
doctypes:"Doctype",
langcode:"Код языка",
langdir:"Направление текста",
ltr:"Слева направо",
rtl:"Справа налево",
xml_pi:"Объявление XML",
encoding:"Кодировка символов",
appearance_bgprops:"Свойства фона",
appearance_marginprops:"Поля страницы",
appearance_linkprops:"Цвета ссылки",
appearance_textprops:"Свойства текста",
bgcolor:"Цвет фона",
bgimage:"Фоновое изображение",
left_margin:"Левое поле",
right_margin:"Правое поле",
top_margin:"Верхнее поле",
bottom_margin:"Нижнее поле",
text_color:"Цвет текста",
font_size:"Размер шрифта",
font_face:"Вид шрифта",
link_color:"Цвет ссылки",
hover_color:"Цвет ссылки при наведении",
visited_color:"Цвет посещенной ссылки",
active_color:"Цвет активной ссылки",
textcolor:"Цвет",
fontsize:"Размер шрифта",
fontface:"Шрифт",
meta_index_follow:"Индексировать и переходить по ссылкам",
meta_index_nofollow:"Индексировать, но НЕ переходить по ссылкам",
meta_noindex_follow:"НЕ индексировать, но переходить по ссылкам",
meta_noindex_nofollow:"НЕ индексировать и НЕ переходить по ссылкам",
appearance_style:"Таблица стилей и свойства стиля",
stylesheet:"Таблица стилей",
style:"Стиль",
author:"Автор",
copyright:"Авторские права",
add:"Добавить новый элемент",
remove:"Удалить выбранный элемент",
moveup:"Передвинуть выбранный элемент выше",
movedown:"Передвинуть выбранный элемент ниже",
head_elements:"Элементы заголовка",
info:"Информация",
add_title:"Заголовок (title)",
add_meta:"Мета-данные",
add_script:"Скрипт (script)",
add_style:"Стиль (style)",
add_link:"Ссылка",
add_base:"Base",
add_comment:"Комментарий",
title_element:"Заголовок (title)",
script_element:"Скрипт (script)",
style_element:"Стиль (style)",
base_element:"Base",
link_element:"Ссылка",
meta_element:"Мета-данные",
comment_element:"Комментарий",
src:"Src",
language:"Язык",
href:"Href",
target:"Target",
type:"Type",
charset:"Кодировка",
defer:"Defer",
media:"Media",
properties:"Свойства",
name:"Название",
value:"Значение",
content:"Содержимое",
rel:"Rel",
rev:"Rev",
hreflang:"Href lang",
general_props:"Общее",
advanced_props:"Дополнительно"
});