// Русские языковые переменные
// Localized Авторские права (C) 2006 - 2009 Joom.Ru - Русский Дом Joomla! Все права защищены.
// Локализатор: (c) Oleg M. (joomru@gmail.com)
// Последнее изменение 16.07.2009

tinyMCE.addI18n('ru.media_dlg',{
title:"Вставка/Изменение медиа",
general:"Основные",
advanced:"Дополнительные",
file:"Файл/URL",
list:"Список",
size:"Размеры",
preview:"Предпросмотр",
constrain_proportions:"Сохранять пропорции",
type:"Тип",
id:"Id",
name:"Имя",
class_name:"Класс",
vspace:"Вертикальные отступы",
hspace:"Горизонтальные отступы",
play:"Автопроигрывание",
loop:"Циклически",
menu:"Показать меню",
quality:"Качество",
scale:"Масштаб",
align:"Выравнивание",
salign:"S-Выравнивание",
wmode:"W-Режим",
bgcolor:"Фон",
base:"База",
flashvars:"Переменные флеша",
liveconnect:"SWLiveConnect",
autohref:"Автодобавление HREF",
cache:"Кеш",
hidden:"Скрыть",
controller:"Контроллер",
kioskmode:"Режим киоска",
playeveryframe:"Проигрывать каждый фрэйм",
targetcache:"Путь к кэшу",
correction:"Без корекции",
enablejavascript:"Разрешить JavaScript",
starttime:"Время начала",
endtime:"Время окончания",
href:"Ссылка",
qtsrcchokespeed:"Скорость",
target:"Назначение",
volume:"Громкость",
autostart:"Авто запуск",
enabled:"Разрешен",
fullscreen:"Полноэкранный",
invokeurls:"Вызываемые ссылки",
mute:"Выключить",
stretchtofit:"Вписать",
windowlessvideo:"Оконное видео",
balance:"Баланс",
baseurl:"Базовая ссылка",
captioningid:"Заголовочный id",
currentmarker:"Текущая метка",
currentposition:"Текущая позиция",
defaultframe:"Фрейм по умолчанию",
playcount:"Количество проигрываний",
rate:"Оценка",
uimode:"Режим UI",
flash_options:"Параметры Flash",
qt_options:"Параметры Quicktime",
wmp_options:"Параметры Windows media player",
rmp_options:"Параметры Real media player",
shockwave_options:"Параметры Shockwave",
autogotourl:"Авто переход по ссылке",
center:"По центру",
imagestatus:"Статус изображения",
maintainaspect:"Вид поддержки",
nojava:"Без java",
prefetch:"Предзагрузка",
shuffle:"Случайно",
console:"Консоль",
numloop:"Число повторений",
controls:"Управление",
scriptcallbacks:"Скрипт вызова",
swstretchstyle:"Стиль растягивания",
swstretchhalign:"Растягивание H-Align",
swstretchvalign:"Растягивание V-Align",
sound:"Звук",
progress:"Прогресс",
qtsrc:"Источник QT",
qt_stream_warn:"Потоковые ресурсы должны быть добавлены в поле Источник QT на вкладке расширенных параметров.\nВы также должны добавить непотоковые версии в поле Источник.",
align_top:"Вверху",
align_right:"Справа",
align_bottom:"Внизу",
align_left:"Слева",
align_center:"По центру",
align_top_left:"Слева вверху",
align_top_right:"Справа вверху",
align_bottom_left:"Слева внизу",
align_bottom_right:"Справа внизу",
flv_options:"Параметры Flash-видео",
flv_scalemode:"Режим масштабирования",
flv_buffer:"Буфер",
flv_startimage:"Изображение при запуске",
flv_starttime:"Время начала",
flv_defaultvolume:"Громкость по умолчанию",
flv_hiddengui:"Спрятать GUI",
flv_autostart:"Авто старт",
flv_loop:"Число повторов",
flv_showscalemodes:"Показать шкалы масштабирования",
flv_smoothvideo:"Сглаживать видео",
flv_jscallback:"Обратный вызов JS"
});