// Русские языковые переменные
// Localized Авторские права (C) 2006 - 2009 Joom.Ru - Русский Дом Joomla! Все права защищены.
// Локализатор: (c) Oleg M. (joomru@gmail.com)
// Последнее изменение 17.07.2009

tinyMCE.addI18n('ru.style_dlg',{
title:"Изменение стиля CSS",
apply:"Применить",
text_tab:"Текст",
background_tab:"Фон",
block_tab:"Блок",
box_tab:"Бокс",
border_tab:"Граница",
list_tab:"Список",
positioning_tab:"Позиционирование",
text_props:"Текст",
text_font:"Шрифт",
text_size:"Размер",
text_weight:"Ширина",
text_style:"Стиль",
text_variant:"Вариант",
text_lineheight:"Высота строки",
text_case:"Регистр",
text_color:"Цвет",
text_decoration:"Оформление",
text_overline:"надчеркнутый",
text_underline:"подчеркнутый",
text_striketrough:"зачеркнутый",
text_blink:"мерцающий",
text_none:"нет",
background_color:"Цвет фона",
background_image:"Фоновое изображение",
background_repeat:"Повторение",
background_attachment:"Прокрутка",
background_hpos:"Горизонтальное положение",
background_vpos:"Вертикальное положение",
block_wordspacing:"Интервал между словами",
block_letterspacing:"Интервал между буквами",
block_vertical_alignment:"Вертикальное выравнивание",
block_text_align:"Выравнивание текста",
block_text_indent:"Отступ текста",
block_whitespace:"Интервал",
block_display:"Показывать",
box_width:"Ширина",
box_height:"Высота",
box_float:"Выравнивание с обтеканием",
box_clear:"Запрет обтекания",
padding:"Отступ",
same:"Применять ко всем",
top:"Вверху",
right:"Справа",
bottom:"Внизу",
left:"Слева",
margin:"Поле",
style:"Стиль",
width:"Ширина",
height:"Высота",
color:"Цвет",
list_type:"Тип",
bullet_image:"Маркер абзаца",
position:"Положение",
positioning_type:"Тип",
visibility:"Прозрачность",
zindex:"Наложение",
overflow:"Переполнение",
placement:"Размещение",
clip:"Позиционирование"
});